---
- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    force: yes

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
  become: yes
  become_method: sudo

- name: Create a new database with name 'bikes'
  mysql_db:
    name: bikes
    state: present
- mysql_user:
    name: bikes
    password: test
    priv: 'bikes.*:ALL'
    state: present