---
- name: Add Nginx repo
  apt_repository:
    repo: ppa:nginx/development

- name: Install Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Check Nginx configs exist
  stat: path=/etc/nginx/.git
  register: git_exists

- name: Remove default Nginx configs
  file:
    path: /etc/nginx
    state: absent
  when: not git_exists.stat.exists

- name: Clone Nginx configs
  git:
    repo: https://github.com/A5hleyRich/wordpress-nginx.git
    dest: /etc/nginx
    version: master
    force: yes
  when: not git_exists.stat.exists

- name: Symlink default site
  file: 
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: Copy across new virtual host for our test.vm
  template:
    src=test.vm.conf.j2
    dest=/etc/nginx/sites-available/test.vm.conf

- name: Enable new vagrant virtual host for our test.vm
  file:
    src=/etc/nginx/sites-available/test.vm.conf
    dest=/etc/nginx/sites-enabled/test.vm.conf
    state=link    

- name: Set Nginx user
  lineinfile: 
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ username }};"
    state: present
  notify: restart nginx